export const TIMELINE_SLOT_MINUTES = 30;
export const EXTENDED_SCHEDULED_PILL_MINUTES = TIMELINE_SLOT_MINUTES;
export const TIMELINE_SLOT_HEIGHT_PX = 330;
export const TIMELINE_PILL_STRIP_TOP_OFFSET_PX = 36;
export const TIMELINE_SCHEDULED_PILL_MIN_HEIGHT_PX = 86;
export const TIMELINE_POINT_PILL_HEIGHT_PX = 69;
export const MAX_TIMELINE_PILL_INDIVIDUAL_COLUMNS = 2;
export const MAX_TIMELINE_PILL_COLUMNS = 2;
