export const TIMELINE_SLOT_MINUTES = 30;
export const EXTENDED_SCHEDULED_PILL_MINUTES = TIMELINE_SLOT_MINUTES;
export const DETAIL_SEPARATOR = ' \u2022 ';
// Keep in sync with styles/tokens.css (--itinerary-half-hour-slot-height, etc.).
export const TIMELINE_SLOT_HEIGHT_PX = 730;
export const TIMELINE_PILL_STRIP_TOP_OFFSET_PX = 80;
export const TIMELINE_SCHEDULED_PILL_MIN_CLUSTER_MINUTES = 3;
export const TIMELINE_SCHEDULED_PILL_MIN_CLUSTER_HEIGHT_PX = Math.round(
   (TIMELINE_SCHEDULED_PILL_MIN_CLUSTER_MINUTES / TIMELINE_SLOT_MINUTES)
      * TIMELINE_SLOT_HEIGHT_PX
);
export const TIMELINE_POINT_PILL_HEIGHT_PX = 153;
export const MAX_TIMELINE_PILL_INDIVIDUAL_COLUMNS = 2;
export const MAX_TIMELINE_PILL_COLUMNS = 2;
export const DAY_PLANNER_ACTION_FEEDBACK_DISMISS_MS = 2500;
export const DAY_PLANNER_ACTION_FEEDBACK_FADE_MS = 300;
