CREATE TABLE IF NOT EXISTS AnimalViewingAlert
(  SPECIES             VARCHAR(64) NOT NULL,
   EXHIBIT             VARCHAR(64) NOT NULL,
   ALERT_MESSAGE       TEXT        NOT NULL,
   ALERT_START_DATE    DATE,
   ALERT_END_DATE      DATE,
   PRIMARY KEY (SPECIES, EXHIBIT),
   FOREIGN KEY (SPECIES) REFERENCES Animal(SPECIES),
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(NAME) );
