DROP TABLE IF EXISTS AnimalDaySeasonalViewabilityMultiplier;

CREATE TABLE AnimalDaySeasonalViewabilityMultiplier
(  SPECIES  VARCHAR(64) NOT NULL,
   EXHIBIT  VARCHAR(64) NOT NULL,
   MONTH    INTEGER     NOT NULL CHECK (MONTH BETWEEN 1 AND 12),
   DAY      INTEGER     NOT NULL CHECK (DAY BETWEEN 1 AND 31),
   VALUE    FLOAT       NOT NULL CHECK (VALUE BETWEEN 0.0 AND 1.0),
   FOREIGN KEY (SPECIES, EXHIBIT) REFERENCES Enclosure(SPECIES, EXHIBIT),
   PRIMARY KEY (SPECIES, EXHIBIT, MONTH, DAY) );
