CREATE TABLE IF NOT EXISTS AnimalVisibilitySchedule
(  SPECIES               VARCHAR(64) NOT NULL,
   EXHIBIT               VARCHAR(64) NOT NULL,
   SCHEDULE_START_DATE   DATE,
   SCHEDULE_END_DATE     DATE,
   DAILY_START_TIME      VARCHAR(8) NOT NULL,
   DAILY_END_TIME        VARCHAR(8) NOT NULL,
   VIEWING_MESSAGE       TEXT,
   PRIMARY KEY (SPECIES, EXHIBIT),
   FOREIGN KEY (SPECIES) REFERENCES Animal(SPECIES),
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(NAME) );
