CREATE TABLE IF NOT EXISTS AnimalStatus
(  SPECIES              VARCHAR(64) NOT NULL,
   EXHIBIT              VARCHAR(64) NOT NULL,
   IS_OFF_DISPLAY       BOOL        NOT NULL DEFAULT 0,
   VIEWING_SCOPE        TEXT        NOT NULL,
   OFF_DISPLAY_MESSAGE  TEXT,
   OFF_DISPLAY_START    DATE,
   OFF_DISPLAY_END      DATE,
   PRIMARY KEY (SPECIES, EXHIBIT, VIEWING_SCOPE),
   FOREIGN KEY (SPECIES) REFERENCES Animal(SPECIES),
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(NAME) );
