CREATE TABLE IF NOT EXISTS AttractionScheduleOverride
(  ATTRACTION            VARCHAR(64) NOT NULL,
   OVERRIDE_START_DATE   DATE        NOT NULL,
   OVERRIDE_END_DATE     DATE,
   IS_CLOSED             BOOL        NOT NULL DEFAULT 1,
   OVERRIDE_MESSAGE      TEXT,
   PRIMARY KEY (ATTRACTION, OVERRIDE_START_DATE),
   FOREIGN KEY (ATTRACTION) REFERENCES Attraction(NAME) );
