DROP TABLE IF EXISTS AttractionAnimal;

CREATE TABLE AttractionAnimal
(  ATTRACTION       VARCHAR(64) NOT NULL,
   SPECIES          VARCHAR(64) NOT NULL,
   EXHIBIT          VARCHAR(64) NOT NULL,
   ENCLOSURE_NAME   VARCHAR(64),
   PRIMARY KEY (ATTRACTION, SPECIES, EXHIBIT),
   FOREIGN KEY (ATTRACTION) REFERENCES Attraction(NAME),
   FOREIGN KEY (SPECIES, EXHIBIT) REFERENCES Enclosure(SPECIES, EXHIBIT),
   FOREIGN KEY (SPECIES, EXHIBIT, ENCLOSURE_NAME)
      REFERENCES EnclosureViewing(SPECIES, EXHIBIT, NAME) );
