CREATE TABLE IF NOT EXISTS AttractionHoursSchedule
(  ATTRACTION                      VARCHAR(64) NOT NULL,
   SCHEDULE_START_DATE             DATE        NOT NULL,
   SCHEDULE_END_DATE               DATE,
   WEEKDAY_START_TIME              VARCHAR(16) NOT NULL,
   WEEKDAY_END_TIME                VARCHAR(16) NOT NULL,
   WEEKEND_HOLIDAY_START_TIME      VARCHAR(16) NOT NULL,
   WEEKEND_HOLIDAY_END_TIME        VARCHAR(16) NOT NULL,
   PRIMARY KEY (ATTRACTION, SCHEDULE_START_DATE),
   FOREIGN KEY (ATTRACTION) REFERENCES Attraction(NAME) );
