DROP TABLE IF EXISTS Enclosure;

CREATE TABLE Enclosure
(  SPECIES                               VARCHAR(64) NOT NULL,
   EXHIBIT                               VARCHAR(64) NOT NULL,
   SEASONAL_VIEWING_SUMMARY              VARCHAR(64) NOT NULL,
   SEASONAL_VIEWING_INFORMATION          TEXT,
   INCLUDE_ALL_VIEWING_SPOTS             BOOL,
   FOREIGN KEY (SPECIES) REFERENCES Animal,
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(Name),
   PRIMARY KEY (SPECIES, EXHIBIT) );
