DROP TABLE IF EXISTS Enclosure;

CREATE TABLE Enclosure
(  SPECIES                               VARCHAR(64) NOT NULL,
   EXHIBIT                               VARCHAR(64) NOT NULL,
   SEASONAL_VIEWING_SUMMARY              VARCHAR(64) NOT NULL,
   SEASONAL_VIEWING_INFORMATION          TEXT,
   DEFAULT_ITINERARY_DURATION_MINUTES    REAL        NOT NULL,
   FOREIGN KEY (SPECIES) REFERENCES Animal,
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(Name),
   PRIMARY KEY (SPECIES, EXHIBIT) );
