CREATE TABLE IF NOT EXISTS ExhibitStatus
(  EXHIBIT           VARCHAR(64) NOT NULL,
   IS_CLOSED         BOOL        NOT NULL DEFAULT 0,
   CLOSED_MESSAGE    TEXT,
   CLOSED_START      DATE,
   CLOSED_END        DATE,
   PRIMARY KEY (EXHIBIT),
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(NAME) );
