DROP TABLE IF EXISTS Exhibit;

CREATE TABLE Exhibit
(  NAME              VARCHAR(64) NOT NULL,
   REGION            VARCHAR(64) NOT NULL,
   FOREIGN KEY (REGION) REFERENCES Region(Name),
   PRIMARY KEY (NAME) );
