DROP TABLE IF EXISTS GiftShopDaySeasonalAvailabilityMultiplier;

CREATE TABLE GiftShopDaySeasonalAvailabilityMultiplier
(  GIFT_SHOP              VARCHAR(64) NOT NULL,
   MONTH                  INTEGER     NOT NULL CHECK (MONTH BETWEEN 1 AND 12),
   DAY                    INTEGER     NOT NULL CHECK (DAY BETWEEN 1 AND 31),
   WEEKDAY_VALUE          FLOAT       NOT NULL CHECK (WEEKDAY_VALUE BETWEEN 0.0 AND 1.0),
   WEEKEND_HOLIDAY_VALUE  FLOAT       NOT NULL CHECK (WEEKEND_HOLIDAY_VALUE BETWEEN 0.0 AND 1.0),
   FOREIGN KEY (GIFT_SHOP) REFERENCES GiftShop(NAME),
   PRIMARY KEY (GIFT_SHOP, MONTH, DAY) );
