CREATE TABLE IF NOT EXISTS GiftShopScheduleOverride
(  GIFT_SHOP             VARCHAR(64) NOT NULL,
   OVERRIDE_START_DATE   DATE        NOT NULL,
   OVERRIDE_END_DATE     DATE,
   IS_CLOSED             BOOL        NOT NULL DEFAULT 1,
   OVERRIDE_MESSAGE      TEXT,
   PRIMARY KEY (GIFT_SHOP, OVERRIDE_START_DATE),
   FOREIGN KEY (GIFT_SHOP) REFERENCES GiftShop(NAME) );
