CREATE TABLE IF NOT EXISTS GuardiansTalkOccurrence
(  TALK_NAME             VARCHAR(64) NOT NULL,
   LOCATION              VARCHAR(64) NOT NULL,
   OCCURRENCE_DATE       DATE        NOT NULL,
   TALK_TIME             TEXT        NOT NULL,
   PRIMARY KEY (TALK_NAME, LOCATION, OCCURRENCE_DATE, TALK_TIME),
   FOREIGN KEY (TALK_NAME, LOCATION) REFERENCES MeetTheGuardiansTalk(NAME, LOCATION) );
