DROP TABLE IF EXISTS GuardiansTalkAnimal;

CREATE TABLE GuardiansTalkAnimal
(  TALK_NAME  VARCHAR(64) NOT NULL,
   LOCATION   VARCHAR(64) NOT NULL,
   SPECIES    VARCHAR(64) NOT NULL,
   EXHIBIT    VARCHAR(64) NOT NULL,
   PRIMARY KEY (TALK_NAME, LOCATION, SPECIES, EXHIBIT),
   FOREIGN KEY (TALK_NAME, LOCATION) REFERENCES MeetTheGuardiansTalk(NAME, LOCATION),
   FOREIGN KEY (SPECIES, EXHIBIT) REFERENCES Enclosure(SPECIES, EXHIBIT) );
