CREATE TABLE IF NOT EXISTS GuardiansTalkCancellation
(  TALK_NAME             VARCHAR(64) NOT NULL,
   LOCATION              VARCHAR(64) NOT NULL,
   CANCELLATION_DATE     DATE        NOT NULL,
   TALK_TIME             TEXT        NOT NULL,
   PRIMARY KEY (TALK_NAME, LOCATION, CANCELLATION_DATE, TALK_TIME),
   FOREIGN KEY (TALK_NAME, LOCATION) REFERENCES MeetTheGuardiansTalk(NAME, LOCATION) );
