DROP TABLE IF EXISTS GuestService;

CREATE TABLE GuestService
(  SERVICE_TYPE  TEXT  NOT NULL,
   X_COORD       FLOAT NOT NULL,
   Y_COORD       FLOAT NOT NULL,
   PRIMARY KEY (SERVICE_TYPE, X_COORD, Y_COORD) );
