CREATE TABLE IF NOT EXISTS ItineraryWalkRouteLeg
(  LEG_SEQUENCE               INTEGER     NOT NULL,
   FROM_ITEM_KEY              TEXT        NOT NULL,
   TO_ITEM_KEY                TEXT        NOT NULL,
   FROM_SCHEDULE_ITEM_KIND    TEXT        NOT NULL,
   TO_SCHEDULE_ITEM_KIND      TEXT        NOT NULL,
   FROM_POINT_SEQUENCE        INTEGER     NOT NULL,
   TO_POINT_SEQUENCE          INTEGER     NOT NULL,
   TRAVEL_TIME_MINUTES        INTEGER     NOT NULL,
   PRIMARY KEY ( LEG_SEQUENCE ) );
