CREATE TABLE IF NOT EXISTS ItineraryTransportation
(  TRANSPORTATION        VARCHAR(64) NOT NULL,
   OLD_LIKELIHOOD        INTEGER,
   NEW_LIKELIHOOD        INTEGER,
   ADDED_AS_ATTRACTION   BOOL        NOT NULL,
   START_TIME            TEXT,
   END_TIME              TEXT,
   ROUTE                 VARCHAR(64),
   PRIMARY KEY ( TRANSPORTATION, ADDED_AS_ATTRACTION ),
   FOREIGN KEY ( TRANSPORTATION ) REFERENCES Transportation(NAME) );
