CREATE TABLE IF NOT EXISTS ItineraryAnimal
(  SPECIES              VARCHAR(64) NOT NULL,
   EXHIBIT              VARCHAR(64) NOT NULL,
   ENCLOSURE_NAME       VARCHAR(64),
   OLD_LIKELIHOOD       INTEGER,
   NEW_LIKELIHOOD       INTEGER,
   IS_ADDED             BOOL        NOT NULL DEFAULT 0,
   START_TIME           TEXT,
   END_TIME             TEXT,
   PRIMARY KEY ( SPECIES, EXHIBIT, ENCLOSURE_NAME ),
   FOREIGN KEY ( SPECIES, EXHIBIT, ENCLOSURE_NAME )
      REFERENCES EnclosureViewing( SPECIES, EXHIBIT, NAME ) );
