CREATE TABLE IF NOT EXISTS ItineraryAttraction
(  ATTRACTION           VARCHAR(64) NOT NULL,
   OLD_LIKELIHOOD       INTEGER,
   NEW_LIKELIHOOD       INTEGER,
   START_TIME           TEXT,
   END_TIME             TEXT,
   PRIMARY KEY ( ATTRACTION ),
   FOREIGN KEY ( ATTRACTION ) REFERENCES Attraction(NAME) );
