CREATE TABLE IF NOT EXISTS ItineraryTransportation
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   OLD_LIKELIHOOD     INTEGER,
   NEW_LIKELIHOOD     INTEGER,
   START_TIME         TEXT,
   END_TIME           TEXT,
   PRIMARY KEY ( TRANSPORTATION ),
   FOREIGN KEY ( TRANSPORTATION ) REFERENCES Transportation(NAME) );
