CREATE TABLE IF NOT EXISTS ItineraryTransportationLeg
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   FROM_STATION       VARCHAR(64) NOT NULL,
   TO_STATION         VARCHAR(64) NOT NULL,
   START_TIME         TEXT        NOT NULL,
   END_TIME           TEXT        NOT NULL,
   PRIMARY KEY ( TRANSPORTATION, START_TIME ),
   FOREIGN KEY ( TRANSPORTATION )
      REFERENCES ItineraryTransportation(TRANSPORTATION),
   FOREIGN KEY ( TRANSPORTATION, FROM_STATION, TO_STATION )
      REFERENCES TransportationLeg(TRANSPORTATION, FROM_STATION, TO_STATION) );
