CREATE TABLE IF NOT EXISTS ItineraryWildEncounter
(  WILD_ENCOUNTER       VARCHAR(64) NOT NULL,
   START_TIME           TEXT,
   END_TIME             TEXT,
   IS_DELETED           BOOL        NOT NULL DEFAULT 0,
   PRIMARY KEY ( WILD_ENCOUNTER ),
   FOREIGN KEY ( WILD_ENCOUNTER ) REFERENCES WildEncounter(NAME) );
