CREATE TABLE IF NOT EXISTS ItineraryTransportationRouteMarker
(  TRANSPORTATION        VARCHAR(64) NOT NULL,
   ADDED_AS_ATTRACTION   BOOL        NOT NULL,
   SEQUENCE              INTEGER     NOT NULL,
   MARKER_ORDER          INTEGER     NOT NULL,
   MARKER_ID             VARCHAR(64) NOT NULL,
   PRIMARY KEY ( TRANSPORTATION, ADDED_AS_ATTRACTION, SEQUENCE, MARKER_ORDER ),
   FOREIGN KEY ( TRANSPORTATION, ADDED_AS_ATTRACTION )
      REFERENCES ItineraryTransportation( TRANSPORTATION, ADDED_AS_ATTRACTION ) );
