CREATE TABLE IF NOT EXISTS ItineraryTransportationRouteMarker
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   SEQUENCE           INTEGER     NOT NULL,
   MARKER_ORDER       INTEGER     NOT NULL,
   MARKER_ID          VARCHAR(64) NOT NULL,
   PRIMARY KEY ( TRANSPORTATION, SEQUENCE, MARKER_ORDER ),
   FOREIGN KEY ( TRANSPORTATION )
      REFERENCES ItineraryTransportation(TRANSPORTATION) );
