DROP TABLE IF EXISTS MeetTheGuardiansTalk;

CREATE TABLE MeetTheGuardiansTalk
(  NAME             VARCHAR(64) NOT NULL,
   LOCATION         VARCHAR(64) NOT NULL,
   X_COORD          FLOAT       NOT NULL,
   Y_COORD          FLOAT       NOT NULL,
   MAXIMUM_DURATION INTEGER     NOT NULL,
   FOREIGN KEY (LOCATION)  REFERENCES Exhibit(NAME),
   PRIMARY KEY (NAME, LOCATION) );
