DROP TABLE IF EXISTS Pavilion;

CREATE TABLE Pavilion
(  NAME        VARCHAR(64) NOT NULL,
   REGION      VARCHAR(64),
   DESCRIPTION TEXT        NOT NULL,
   X_COORD     FLOAT       NOT NULL,
   Y_COORD     FLOAT       NOT NULL,
   FOREIGN KEY (REGION) REFERENCES Region(Name),
   PRIMARY KEY (NAME) );
