CREATE TABLE IF NOT EXISTS RestaurantScheduleOverride
(  RESTAURANT            VARCHAR(64) NOT NULL,
   OVERRIDE_START_DATE   DATE        NOT NULL,
   OVERRIDE_END_DATE     DATE,
   IS_CLOSED             BOOL        NOT NULL DEFAULT 1,
   OVERRIDE_MESSAGE      TEXT,
   PRIMARY KEY (RESTAURANT, OVERRIDE_START_DATE),
   FOREIGN KEY (RESTAURANT) REFERENCES Restaurant(NAME) );
