DROP TABLE IF EXISTS RestaurantDaySeasonalAvailabilityMultiplier;

CREATE TABLE RestaurantDaySeasonalAvailabilityMultiplier
(  RESTAURANT              VARCHAR(64) NOT NULL,
   MONTH                   INTEGER     NOT NULL CHECK (MONTH BETWEEN 1 AND 12),
   DAY                     INTEGER     NOT NULL CHECK (DAY BETWEEN 1 AND 31),
   WEEKDAY_VALUE           FLOAT       NOT NULL CHECK (WEEKDAY_VALUE BETWEEN 0.0 AND 1.0),
   WEEKEND_HOLIDAY_VALUE   FLOAT       NOT NULL CHECK (WEEKEND_HOLIDAY_VALUE BETWEEN 0.0 AND 1.0),
   FOREIGN KEY (RESTAURANT) REFERENCES Restaurant(NAME),
   PRIMARY KEY (RESTAURANT, MONTH, DAY) );
