CREATE TABLE IF NOT EXISTS RestroomAlert
(  RESTROOM            VARCHAR(64) NOT NULL,
   ALERT_MESSAGE       TEXT        NOT NULL,
   ALERT_START_DATE    DATE,
   ALERT_END_DATE      DATE,
   PRIMARY KEY (RESTROOM),
   FOREIGN KEY (RESTROOM) REFERENCES Restroom(TITLE) );
