CREATE TABLE IF NOT EXISTS RestroomStatus
(  RESTROOM          VARCHAR(64) NOT NULL,
   IS_CLOSED         BOOL        NOT NULL DEFAULT 0,
   CLOSED_MESSAGE    TEXT,
   CLOSED_START      DATE,
   CLOSED_END        DATE,
   PRIMARY KEY (RESTROOM),
   FOREIGN KEY (RESTROOM) REFERENCES Restroom(TITLE) );
