CREATE TABLE IF NOT EXISTS TransportationRouteSchedule
(  TRANSPORTATION        VARCHAR(64) NOT NULL,
   SCHEDULE_START_DATE   DATE        NOT NULL,
   SCHEDULE_END_DATE     DATE,
   ROUTE                 VARCHAR(64) NOT NULL,
   PRIMARY KEY (TRANSPORTATION, SCHEDULE_START_DATE),
   FOREIGN KEY (TRANSPORTATION)
      REFERENCES Transportation(NAME),
   FOREIGN KEY (TRANSPORTATION, ROUTE)
      REFERENCES TransportationRoute(TRANSPORTATION, ROUTE) );
