DROP TABLE IF EXISTS TransportationAnimal;

CREATE TABLE TransportationAnimal
(  TRANSPORTATION      VARCHAR(64) NOT NULL,
   FROM_STATION        VARCHAR(64) NOT NULL,
   TO_STATION          VARCHAR(64) NOT NULL,
   SPECIES             VARCHAR(64) NOT NULL,
   EXHIBIT             VARCHAR(64) NOT NULL,
   ENCLOSURE_NAME      VARCHAR(64),
   PRIMARY KEY ( SPECIES, EXHIBIT, ENCLOSURE_NAME ),
   FOREIGN KEY ( TRANSPORTATION, FROM_STATION, TO_STATION )
      REFERENCES TransportationLeg( TRANSPORTATION, FROM_STATION, TO_STATION ),
   FOREIGN KEY ( SPECIES, EXHIBIT, ENCLOSURE_NAME )
      REFERENCES EnclosureViewing( SPECIES, EXHIBIT, NAME ) );
