DROP TABLE IF EXISTS TransportationRouteLeg;

CREATE TABLE TransportationRouteLeg
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   ROUTE              VARCHAR(64) NOT NULL,
   FROM_STATION       VARCHAR(64) NOT NULL,
   TO_STATION         VARCHAR(64) NOT NULL,
   PRIMARY KEY (TRANSPORTATION, ROUTE, FROM_STATION, TO_STATION),
   FOREIGN KEY (TRANSPORTATION, ROUTE)
      REFERENCES TransportationRoute(TRANSPORTATION, ROUTE),
   FOREIGN KEY (TRANSPORTATION, FROM_STATION, TO_STATION)
      REFERENCES TransportationLeg(TRANSPORTATION, FROM_STATION, TO_STATION) );
