DROP TABLE IF EXISTS TransportationRoute;

CREATE TABLE TransportationRoute
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   ROUTE              VARCHAR(64) NOT NULL,
   PRIMARY KEY (TRANSPORTATION, ROUTE),
   FOREIGN KEY (TRANSPORTATION) REFERENCES Transportation(NAME) );
