CREATE TABLE IF NOT EXISTS TransportationStationStatus
(  TRANSPORTATION      VARCHAR(64) NOT NULL,
   STATION             VARCHAR(64) NOT NULL,
   IS_CLOSED           BOOL        NOT NULL DEFAULT 0,
   CLOSED_MESSAGE      TEXT,
   CLOSED_START        DATE,
   CLOSED_END          DATE,
   PRIMARY KEY (TRANSPORTATION, STATION),
   FOREIGN KEY (TRANSPORTATION, STATION)
      REFERENCES TransportationStation(TRANSPORTATION, NAME) );
