DROP TABLE IF EXISTS TransportationRouteStation;

CREATE TABLE TransportationRouteStation
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   ROUTE              VARCHAR(64) NOT NULL,
   STATION            VARCHAR(64) NOT NULL,
   PRIMARY KEY (TRANSPORTATION, ROUTE, STATION),
   FOREIGN KEY (TRANSPORTATION, ROUTE)
      REFERENCES TransportationRoute(TRANSPORTATION, ROUTE),
   FOREIGN KEY (TRANSPORTATION, STATION)
      REFERENCES TransportationStation(TRANSPORTATION, NAME) );
