DROP TABLE IF EXISTS TransportationRouteLegMarker;

CREATE TABLE TransportationRouteLegMarker
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   ROUTE              VARCHAR(64) NOT NULL,
   FROM_STATION       VARCHAR(64) NOT NULL,
   TO_STATION         VARCHAR(64) NOT NULL,
   MARKER_ID          VARCHAR(64) NOT NULL,
   PRIMARY KEY (TRANSPORTATION, ROUTE, FROM_STATION, TO_STATION, MARKER_ID),
   UNIQUE (MARKER_ID),
   FOREIGN KEY (TRANSPORTATION, ROUTE, FROM_STATION, TO_STATION)
      REFERENCES TransportationRouteLeg(
         TRANSPORTATION,
         ROUTE,
         FROM_STATION,
         TO_STATION ) );
