DROP TABLE IF EXISTS TransportationLeg;

CREATE TABLE TransportationLeg
(  TRANSPORTATION      VARCHAR(64) NOT NULL,
   FROM_STATION        VARCHAR(64) NOT NULL,
   TO_STATION          VARCHAR(64) NOT NULL,
   DURATION_MINUTES    INTEGER     NOT NULL,
   PRIMARY KEY (TRANSPORTATION, FROM_STATION, TO_STATION),
   FOREIGN KEY (TRANSPORTATION, FROM_STATION)
      REFERENCES TransportationStation(TRANSPORTATION, NAME),
   FOREIGN KEY (TRANSPORTATION, TO_STATION)
      REFERENCES TransportationStation(TRANSPORTATION, NAME) );
