DROP TABLE IF EXISTS TransportationDayRoute;

CREATE TABLE TransportationDayRoute
(  TRANSPORTATION     VARCHAR(64) NOT NULL,
   MONTH              INTEGER     NOT NULL CHECK (MONTH BETWEEN 1 AND 12),
   DAY                INTEGER     NOT NULL CHECK (DAY BETWEEN 1 AND 31),
   ROUTE              VARCHAR(64) NOT NULL,
   PRIMARY KEY (TRANSPORTATION, MONTH, DAY),
   FOREIGN KEY (TRANSPORTATION, ROUTE)
      REFERENCES TransportationRoute(TRANSPORTATION, ROUTE) );
