DROP TABLE IF EXISTS WildEncounter;

CREATE TABLE WildEncounter
(  NAME             TEXT    NOT NULL,
   MEETING_SPOT     TEXT    NOT NULL,
   LINK             TEXT    NOT NULL,
   MAXIMUM_DURATION INTEGER NOT NULL,
   FOREIGN KEY (MEETING_SPOT) REFERENCES WildEncounterMeetingSpot(NAME),
   PRIMARY KEY (NAME) );
