CREATE TABLE IF NOT EXISTS WildEncounterCancellation
(  WILD_ENCOUNTER        VARCHAR(64) NOT NULL,
   CANCELLATION_DATE     DATE        NOT NULL,
   ENCOUNTER_TIME        TEXT        NOT NULL,
   PRIMARY KEY (WILD_ENCOUNTER, CANCELLATION_DATE, ENCOUNTER_TIME),
   FOREIGN KEY (WILD_ENCOUNTER) REFERENCES WildEncounter(NAME) );
