CREATE TABLE IF NOT EXISTS ZooUpdate
(  TITLE          VARCHAR(128) NOT NULL,
   DESCRIPTION    TEXT         NOT NULL,
   UPDATE_TYPE    VARCHAR(32)  NOT NULL,
   START_DATE     DATE         NOT NULL,
   END_DATE       DATE,
   PRIMARY KEY (TITLE, START_DATE) );

CREATE UNIQUE INDEX IF NOT EXISTS ZooUpdateTitleStartDateIndex
   ON ZooUpdate (TITLE, START_DATE);
