CREATE TABLE IF NOT EXISTS ZooEvent
(  NAME         VARCHAR(128) NOT NULL,
   LOCATION     VARCHAR(128) NOT NULL,
   DESCRIPTION  TEXT         NOT NULL,
   LINK         TEXT         NOT NULL,
   START_DATE   DATE         NOT NULL,
   END_DATE     DATE,
   PRIMARY KEY (NAME, START_DATE) );

CREATE UNIQUE INDEX IF NOT EXISTS ZooEventNameStartDateIndex
   ON ZooEvent (NAME, START_DATE);
