DROP TABLE IF EXISTS ZooHours;

CREATE TABLE ZooHours
(  OPERATING_DATE       DATE       NOT NULL PRIMARY KEY,
   EARLY_ADMISSION_TIME  VARCHAR(5),
   OPEN_TIME             VARCHAR(5) NOT NULL,
   LAST_ADMISSION_TIME   VARCHAR(5) NOT NULL,
   CLOSE_TIME            VARCHAR(5) NOT NULL );
