CREATE TABLE IF NOT EXISTS ZoomobileStationStatus
(  ZOOMOBILE_STATION VARCHAR(64) NOT NULL,
   IS_CLOSED         BOOL        NOT NULL DEFAULT 0,
   CLOSED_MESSAGE    TEXT,
   CLOSED_START      DATE,
   CLOSED_END        DATE,
   PRIMARY KEY (ZOOMOBILE_STATION),
   FOREIGN KEY (ZOOMOBILE_STATION) REFERENCES ZoomobileStation(NAME) );
