CREATE TABLE IF NOT EXISTS ZoomobileRouteSchedule
(  SCHEDULE_START_DATE   DATE        NOT NULL,
   SCHEDULE_END_DATE     DATE,
   ROUTE                 VARCHAR(64) NOT NULL,
   PRIMARY KEY (SCHEDULE_START_DATE) );
