DROP TABLE IF EXISTS ZoomobileDayRoute;

CREATE TABLE ZoomobileDayRoute
(  MONTH   INTEGER     NOT NULL CHECK (MONTH BETWEEN 1 AND 12),
   DAY     INTEGER     NOT NULL CHECK (DAY BETWEEN 1 AND 31),
   ROUTE   VARCHAR(16) NOT NULL CHECK (ROUTE IN ('summer', 'winter')),
   PRIMARY KEY (MONTH, DAY) );
