import { loadGiftShops, populateGiftShopDropdown } from '../../utils.js';
import { createWeeklyAvailabilityController } from '../../shared/weeklyAvailabilityController.js';

export function createGiftShopOpenController({
   showButtonEl,
   panelEl,
   cancelButtonEl,
   submitButtonEl,
   statusEl,
   giftShopEl,
   presetEl,
   startDateEl,
   endDateEl,
   mondayEl,
   tuesdayEl,
   wednesdayEl,
   thursdayEl,
   fridayEl,
   saturdayEl,
   sundayEl,
   holidaysOnlyEl,
   messageEl,
   activatePanel,
   hidePanels,
} = {}) {
   return createWeeklyAvailabilityController({
      showButtonEl,
      panelEl,
      cancelButtonEl,
      submitButtonEl,
      statusEl,
      entityEl: giftShopEl,
      presetEl,
      startDateEl,
      endDateEl,
      mondayEl,
      tuesdayEl,
      wednesdayEl,
      thursdayEl,
      fridayEl,
      saturdayEl,
      sundayEl,
      holidaysOnlyEl,
      messageEl,
      activatePanel,
      loadOptions: loadGiftShops,
      populateOptions: populateGiftShopDropdown,
      endpoint: '/set-gift-shop-opening-schedule',
      entityLabel: 'Gift shop',
      optionsLabel: 'gift shops',
      payloadKey: 'giftShop',
      resultName: result => result.gift_shop,
   });
}
