import { loadGiftShops } from '../../options/loaders.js';
import { populateGiftShopDropdown } from '../../options/dropdowns.js';
import { createWeeklyAvailabilityFormController } from '../../forms/weeklyAvailabilityFormController.js';
import { setGiftShopOpeningSchedule } from '../../../api/consoleOperationsApi.js';

export function createGiftShopOpenController({
   showButtonEl,
   panelEl,
   cancelButtonEl,
   submitButtonEl,
   statusEl,
   giftShopEl,
   presetEl,
   startDateEl,
   endDateEl,
   mondayEl,
   tuesdayEl,
   wednesdayEl,
   thursdayEl,
   fridayEl,
   saturdayEl,
   sundayEl,
   holidaysOnlyEl,
   messageEl,
   activatePanel,
   hidePanels,
} = {}) {
   return createWeeklyAvailabilityFormController({
      showButtonEl,
      panelEl,
      cancelButtonEl,
      submitButtonEl,
      statusEl,
      entityEl: giftShopEl,
      presetEl,
      startDateEl,
      endDateEl,
      mondayEl,
      tuesdayEl,
      wednesdayEl,
      thursdayEl,
      fridayEl,
      saturdayEl,
      sundayEl,
      holidaysOnlyEl,
      messageEl,
      activatePanel,
      loadOptions: loadGiftShops,
      populateOptions: populateGiftShopDropdown,
      submitSchedule: setGiftShopOpeningSchedule,
      entityLabel: 'Gift shop',
      optionsLabel: 'gift shops',
      payloadKey: 'giftShop',
      resultName: result => result.gift_shop,
   });
}
