export const ITINERARY_PATH_ARROW_INTERVAL_PX = 60;
export const ITINERARY_PATH_ARROW_SKIP_END_PX = 20;
export const ITINERARY_PATH_ARROW_MIN_PATH_LENGTH_PX = 36;
export const ITINERARY_PATH_ARROW_CURVE_SAMPLE_STEP_PX = 8;
export const ITINERARY_PATH_ARROW_SIDE_OFFSET_PX = 3;
