export class ItineraryPathConstants {
   static ITINERARY_PATH_ARROW_INTERVAL_PX = 60;
   static ITINERARY_PATH_ARROW_SKIP_END_PX = 20;
   static ITINERARY_PATH_ARROW_MIN_PATH_LENGTH_PX = 36;
   static ITINERARY_PATH_ARROW_CURVE_SAMPLE_STEP_PX = 8;
   static ITINERARY_PATH_ARROW_SIDE_OFFSET_PX = 3;
}
