from enum import Enum


class ItineraryErrorType( str, Enum ):
   SUCCESS = 'success'
   ITINERARY_DATE_NOT_SET = 'itineraryDateNotSet'
   TIME_OUT_OF_BOUNDS = 'timeOutOfBounds'
   TIME_ORDER_INVALID = 'timeOrderInvalid'
   SAVE_FAILED = 'saveFailed'
   ACTIVITY_NOT_ON_DAY_SCHEDULE = 'activityNotOnDaySchedule'
   SCHEDULE_WINDOW_UNAVAILABLE = 'scheduleWindowUnavailable'
   ARRIVAL_DEPARTURE_TOO_CLOSE = 'arrivalDepartureTooClose'
   EARLY_ADMISSION_REQUIRES_MEMBERSHIP = 'earlyAdmissionRequiresMembership'
   NO_AVAILABLE_SLOT = 'noAvailableSlot'
   REQUESTED_TIME_NOT_AVAILABLE = 'requestedTimeNotAvailable'
   ITEM_NOT_ON_ITINERARY = 'itemNotOnItinerary'
   ITEM_ALREADY_SCHEDULED = 'itemAlreadyScheduled'
   GUARDIANS_TALK_WILL_UNSCHEDULE_ITEMS = 'guardiansTalkWillUnscheduleItems'
   FIXED_TIME_ITEM_LONG_WAIT = 'fixedTimeItemLongWait'
   GUARDIANS_TALK_WITHOUT_ANIMAL = 'guardiansTalkWithoutAnimal'
   WILD_ENCOUNTER_WILL_UNSCHEDULE_ITEMS = 'wildEncounterWillUnscheduleItems'
   GUARDIANS_TALK_WILD_ENCOUNTER_TIME_CONFLICT = 'guardiansTalkWildEncounterTimeConflict'
   WILD_ENCOUNTER_TIME_CONFLICT = 'wildEncounterTimeConflict'
   BULK_SCHEDULE_ANIMALS_NOT_ENOUGH_TIME = 'bulkScheduleAnimalsNotEnoughTime'
   BULK_SCHEDULE_ANIMALS_ALREADY_SCHEDULED = 'bulkScheduleAnimalsAlreadyScheduled'
   UNSCHEDULE_ALL_NOTHING_SCHEDULED = 'unscheduleAllNothingScheduled'
