import { loadRestaurants, populateRestaurantDropdown } from '../../utils.js';
import { createWeeklyAvailabilityController } from '../../shared/weeklyAvailabilityController.js';

export function createRestaurantOpenController({
   showButtonEl,
   panelEl,
   cancelButtonEl,
   submitButtonEl,
   statusEl,
   restaurantEl,
   presetEl,
   startDateEl,
   endDateEl,
   mondayEl,
   tuesdayEl,
   wednesdayEl,
   thursdayEl,
   fridayEl,
   saturdayEl,
   sundayEl,
   holidaysOnlyEl,
   messageEl,
   activatePanel,
   hidePanels,
} = {}) {
   return createWeeklyAvailabilityController({
      showButtonEl,
      panelEl,
      cancelButtonEl,
      submitButtonEl,
      statusEl,
      entityEl: restaurantEl,
      presetEl,
      startDateEl,
      endDateEl,
      mondayEl,
      tuesdayEl,
      wednesdayEl,
      thursdayEl,
      fridayEl,
      saturdayEl,
      sundayEl,
      holidaysOnlyEl,
      messageEl,
      activatePanel,
      loadOptions: loadRestaurants,
      populateOptions: populateRestaurantDropdown,
      endpoint: '/set-restaurant-opening-schedule',
      entityLabel: 'Restaurant',
      optionsLabel: 'restaurants',
      payloadKey: 'restaurant',
      resultName: result => result.restaurant,
   });
}
