import { loadAttractions, populateAttractionDropdown } from '../../utils.js';
import { createWeeklyAvailabilityController } from '../../shared/weeklyAvailabilityController.js';

export function createAttractionOpenController({
   showButtonEl,
   panelEl,
   cancelButtonEl,
   submitButtonEl,
   statusEl,
   attractionEl,
   presetEl,
   startDateEl,
   endDateEl,
   mondayEl,
   tuesdayEl,
   wednesdayEl,
   thursdayEl,
   fridayEl,
   saturdayEl,
   sundayEl,
   holidaysOnlyEl,
   messageEl,
   activatePanel,
   hidePanels,
} = {}) {
   return createWeeklyAvailabilityController({
      showButtonEl,
      panelEl,
      cancelButtonEl,
      submitButtonEl,
      statusEl,
      entityEl: attractionEl,
      presetEl,
      startDateEl,
      endDateEl,
      mondayEl,
      tuesdayEl,
      wednesdayEl,
      thursdayEl,
      fridayEl,
      saturdayEl,
      sundayEl,
      holidaysOnlyEl,
      messageEl,
      activatePanel,
      loadOptions: loadAttractions,
      populateOptions: populateAttractionDropdown,
      endpoint: '/set-attraction-opening-schedule',
      entityLabel: 'Attraction',
      optionsLabel: 'attractions',
      payloadKey: 'attraction',
      resultName: result => result.attraction,
   });
}
