CREATE TABLE IF NOT EXISTS AttractionScheduleOverride
(  ATTRACTION            VARCHAR(64) NOT NULL,
   OVERRIDE_START_DATE   DATE        NOT NULL,
   OVERRIDE_END_DATE     DATE,
   IS_CLOSED             BOOL        NOT NULL DEFAULT 1,
   OVERRIDE_MESSAGE      TEXT,
   PRIMARY KEY (ATTRACTION, OVERRIDE_START_DATE),
   FOREIGN KEY (ATTRACTION) REFERENCES Attraction(NAME) );

DROP TABLE IF EXISTS AttractionScheduleOverrideMigration;

CREATE TABLE AttractionScheduleOverrideMigration
(  ATTRACTION            VARCHAR(64) NOT NULL,
   OVERRIDE_START_DATE   DATE        NOT NULL,
   OVERRIDE_END_DATE     DATE,
   IS_CLOSED             BOOL        NOT NULL DEFAULT 1,
   OVERRIDE_MESSAGE      TEXT,
   PRIMARY KEY (ATTRACTION, OVERRIDE_START_DATE),
   FOREIGN KEY (ATTRACTION) REFERENCES Attraction(NAME) );

INSERT OR IGNORE INTO AttractionScheduleOverrideMigration (
   ATTRACTION,
   OVERRIDE_START_DATE,
   OVERRIDE_END_DATE,
   IS_CLOSED,
   OVERRIDE_MESSAGE
)
SELECT
   ATTRACTION,
   OVERRIDE_START_DATE,
   OVERRIDE_END_DATE,
   IS_CLOSED,
   OVERRIDE_MESSAGE
FROM AttractionScheduleOverride;

DROP TABLE AttractionScheduleOverride;

ALTER TABLE AttractionScheduleOverrideMigration RENAME TO AttractionScheduleOverride;
