DROP TABLE IF EXISTS RestaurantOpeningScheduleMigration;

CREATE TABLE RestaurantOpeningScheduleMigration
(  RESTAURANT            VARCHAR(64) NOT NULL,
   SCHEDULE_START_DATE   DATE        NOT NULL,
   SCHEDULE_END_DATE     DATE,
   MONDAY                BOOL        NOT NULL DEFAULT 0,
   TUESDAY               BOOL        NOT NULL DEFAULT 0,
   WEDNESDAY             BOOL        NOT NULL DEFAULT 0,
   THURSDAY              BOOL        NOT NULL DEFAULT 0,
   FRIDAY                BOOL        NOT NULL DEFAULT 0,
   SATURDAY              BOOL        NOT NULL DEFAULT 0,
   SUNDAY                BOOL        NOT NULL DEFAULT 0,
   HOLIDAYS_ONLY         BOOL        NOT NULL DEFAULT 0,
   SCHEDULE_MESSAGE      TEXT,
   PRIMARY KEY (RESTAURANT, SCHEDULE_START_DATE),
   FOREIGN KEY (RESTAURANT) REFERENCES Restaurant(NAME) );

INSERT OR IGNORE INTO RestaurantOpeningScheduleMigration (
   RESTAURANT,
   SCHEDULE_START_DATE,
   SCHEDULE_END_DATE,
   MONDAY,
   TUESDAY,
   WEDNESDAY,
   THURSDAY,
   FRIDAY,
   SATURDAY,
   SUNDAY,
   HOLIDAYS_ONLY,
   SCHEDULE_MESSAGE
)
SELECT
   RESTAURANT,
   SCHEDULE_START_DATE,
   SCHEDULE_END_DATE,
   MONDAY,
   TUESDAY,
   WEDNESDAY,
   THURSDAY,
   FRIDAY,
   SATURDAY,
   SUNDAY,
   HOLIDAYS_ONLY,
   SCHEDULE_MESSAGE
FROM RestaurantOpeningSchedule;

DROP TABLE RestaurantOpeningSchedule;

ALTER TABLE RestaurantOpeningScheduleMigration RENAME TO RestaurantOpeningSchedule;

CREATE TABLE IF NOT EXISTS RestaurantScheduleOverride
(  RESTAURANT            VARCHAR(64) NOT NULL,
   OVERRIDE_START_DATE   DATE        NOT NULL,
   OVERRIDE_END_DATE     DATE,
   IS_CLOSED             BOOL        NOT NULL DEFAULT 1,
   OVERRIDE_MESSAGE      TEXT,
   PRIMARY KEY (RESTAURANT, OVERRIDE_START_DATE),
   FOREIGN KEY (RESTAURANT) REFERENCES Restaurant(NAME) );

DROP TABLE IF EXISTS GiftShopOpeningScheduleMigration;

CREATE TABLE GiftShopOpeningScheduleMigration
(  GIFT_SHOP             VARCHAR(64) NOT NULL,
   SCHEDULE_START_DATE   DATE        NOT NULL,
   SCHEDULE_END_DATE     DATE,
   MONDAY                BOOL        NOT NULL DEFAULT 0,
   TUESDAY               BOOL        NOT NULL DEFAULT 0,
   WEDNESDAY             BOOL        NOT NULL DEFAULT 0,
   THURSDAY              BOOL        NOT NULL DEFAULT 0,
   FRIDAY                BOOL        NOT NULL DEFAULT 0,
   SATURDAY              BOOL        NOT NULL DEFAULT 0,
   SUNDAY                BOOL        NOT NULL DEFAULT 0,
   HOLIDAYS_ONLY         BOOL        NOT NULL DEFAULT 0,
   SCHEDULE_MESSAGE      TEXT,
   PRIMARY KEY (GIFT_SHOP, SCHEDULE_START_DATE),
   FOREIGN KEY (GIFT_SHOP) REFERENCES GiftShop(NAME) );

INSERT OR IGNORE INTO GiftShopOpeningScheduleMigration (
   GIFT_SHOP,
   SCHEDULE_START_DATE,
   SCHEDULE_END_DATE,
   MONDAY,
   TUESDAY,
   WEDNESDAY,
   THURSDAY,
   FRIDAY,
   SATURDAY,
   SUNDAY,
   HOLIDAYS_ONLY,
   SCHEDULE_MESSAGE
)
SELECT
   GIFT_SHOP,
   SCHEDULE_START_DATE,
   SCHEDULE_END_DATE,
   MONDAY,
   TUESDAY,
   WEDNESDAY,
   THURSDAY,
   FRIDAY,
   SATURDAY,
   SUNDAY,
   HOLIDAYS_ONLY,
   SCHEDULE_MESSAGE
FROM GiftShopOpeningSchedule;

DROP TABLE GiftShopOpeningSchedule;

ALTER TABLE GiftShopOpeningScheduleMigration RENAME TO GiftShopOpeningSchedule;

CREATE TABLE IF NOT EXISTS GiftShopScheduleOverride
(  GIFT_SHOP             VARCHAR(64) NOT NULL,
   OVERRIDE_START_DATE   DATE        NOT NULL,
   OVERRIDE_END_DATE     DATE,
   IS_CLOSED             BOOL        NOT NULL DEFAULT 1,
   OVERRIDE_MESSAGE      TEXT,
   PRIMARY KEY (GIFT_SHOP, OVERRIDE_START_DATE),
   FOREIGN KEY (GIFT_SHOP) REFERENCES GiftShop(NAME) );
