CREATE TABLE IF NOT EXISTS AnimalStatusMigrated
(  SPECIES              VARCHAR(64) NOT NULL,
   EXHIBIT              VARCHAR(64) NOT NULL,
   VIEWING_SCOPE         TEXT        NOT NULL,
   IS_OFF_DISPLAY       BOOL        NOT NULL DEFAULT 0,
   OFF_DISPLAY_MESSAGE  TEXT,
   OFF_DISPLAY_START    DATE,
   OFF_DISPLAY_END      DATE,
   PRIMARY KEY (SPECIES, EXHIBIT, VIEWING_SCOPE),
   FOREIGN KEY (SPECIES) REFERENCES Animal(SPECIES),
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(NAME) );

INSERT OR REPLACE INTO AnimalStatusMigrated (
   SPECIES,
   EXHIBIT,
   VIEWING_SCOPE,
   IS_OFF_DISPLAY,
   OFF_DISPLAY_MESSAGE,
   OFF_DISPLAY_START,
   OFF_DISPLAY_END
)
SELECT
   SPECIES,
   EXHIBIT,
   'all',
   IS_OFF_DISPLAY,
   OFF_DISPLAY_MESSAGE,
   OFF_DISPLAY_START,
   OFF_DISPLAY_END
FROM AnimalStatus;

DROP TABLE AnimalStatus;

ALTER TABLE AnimalStatusMigrated
RENAME TO AnimalStatus;
