ALTER TABLE AnimalStatus ADD COLUMN IS_OFF_DISPLAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AnimalStatus ADD COLUMN OFF_DISPLAY_MESSAGE TEXT;
ALTER TABLE AnimalStatus ADD COLUMN VIEWING_SCOPE TEXT;
ALTER TABLE AnimalStatus ADD COLUMN OFF_DISPLAY_START DATE;
ALTER TABLE AnimalStatus ADD COLUMN OFF_DISPLAY_END DATE;

ALTER TABLE AnimalVisibilitySchedule ADD COLUMN SCHEDULE_START_DATE DATE;
ALTER TABLE AnimalVisibilitySchedule ADD COLUMN SCHEDULE_END_DATE DATE;
ALTER TABLE AnimalVisibilitySchedule ADD COLUMN DAILY_START_TIME VARCHAR(8) NOT NULL DEFAULT '09:00';
ALTER TABLE AnimalVisibilitySchedule ADD COLUMN DAILY_END_TIME VARCHAR(8) NOT NULL DEFAULT '17:00';
ALTER TABLE AnimalVisibilitySchedule ADD COLUMN VIEWING_MESSAGE TEXT;

ALTER TABLE AnimalViewingAlert ADD COLUMN ALERT_MESSAGE TEXT;
ALTER TABLE AnimalViewingAlert ADD COLUMN ALERT_START_DATE DATE;
ALTER TABLE AnimalViewingAlert ADD COLUMN ALERT_END_DATE DATE;

ALTER TABLE ExhibitStatus ADD COLUMN IS_CLOSED BOOL NOT NULL DEFAULT 0;
ALTER TABLE ExhibitStatus ADD COLUMN CLOSED_MESSAGE TEXT;
ALTER TABLE ExhibitStatus ADD COLUMN CLOSED_START DATE;
ALTER TABLE ExhibitStatus ADD COLUMN CLOSED_END DATE;

ALTER TABLE RestroomStatus ADD COLUMN IS_CLOSED BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestroomStatus ADD COLUMN CLOSED_MESSAGE TEXT;
ALTER TABLE RestroomStatus ADD COLUMN CLOSED_START DATE;
ALTER TABLE RestroomStatus ADD COLUMN CLOSED_END DATE;

ALTER TABLE RestroomAlert ADD COLUMN ALERT_MESSAGE TEXT;
ALTER TABLE RestroomAlert ADD COLUMN ALERT_START_DATE DATE;
ALTER TABLE RestroomAlert ADD COLUMN ALERT_END_DATE DATE;

ALTER TABLE ZooUpdate ADD COLUMN TITLE VARCHAR(128);
ALTER TABLE ZooUpdate ADD COLUMN DESCRIPTION TEXT;
ALTER TABLE ZooUpdate ADD COLUMN UPDATE_TYPE VARCHAR(32);
ALTER TABLE ZooUpdate ADD COLUMN START_DATE DATE;
ALTER TABLE ZooUpdate ADD COLUMN END_DATE DATE;

ALTER TABLE RestaurantOpeningSchedule ADD COLUMN SCHEDULE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN SCHEDULE_END_DATE DATE;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN MONDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN TUESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN WEDNESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN THURSDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN FRIDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN SATURDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN SUNDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN HOLIDAYS_ONLY BOOL NOT NULL DEFAULT 0;
ALTER TABLE RestaurantOpeningSchedule ADD COLUMN SCHEDULE_MESSAGE TEXT;

ALTER TABLE RestaurantScheduleOverride ADD COLUMN OVERRIDE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE RestaurantScheduleOverride ADD COLUMN OVERRIDE_END_DATE DATE;
ALTER TABLE RestaurantScheduleOverride ADD COLUMN IS_CLOSED BOOL NOT NULL DEFAULT 1;
ALTER TABLE RestaurantScheduleOverride ADD COLUMN OVERRIDE_MESSAGE TEXT;

ALTER TABLE GiftShopOpeningSchedule ADD COLUMN SCHEDULE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN SCHEDULE_END_DATE DATE;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN MONDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN TUESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN WEDNESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN THURSDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN FRIDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN SATURDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN SUNDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN HOLIDAYS_ONLY BOOL NOT NULL DEFAULT 0;
ALTER TABLE GiftShopOpeningSchedule ADD COLUMN SCHEDULE_MESSAGE TEXT;

ALTER TABLE GiftShopScheduleOverride ADD COLUMN OVERRIDE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE GiftShopScheduleOverride ADD COLUMN OVERRIDE_END_DATE DATE;
ALTER TABLE GiftShopScheduleOverride ADD COLUMN IS_CLOSED BOOL NOT NULL DEFAULT 1;
ALTER TABLE GiftShopScheduleOverride ADD COLUMN OVERRIDE_MESSAGE TEXT;

ALTER TABLE AppSetting ADD COLUMN SETTING_KEY VARCHAR(64) NOT NULL;
ALTER TABLE AppSetting ADD COLUMN SETTING_VALUE VARCHAR(64) NOT NULL DEFAULT "";

ALTER TABLE AttractionOpeningSchedule ADD COLUMN SCHEDULE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN SCHEDULE_END_DATE DATE;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN MONDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN TUESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN WEDNESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN THURSDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN FRIDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN SATURDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN SUNDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN HOLIDAYS_ONLY BOOL NOT NULL DEFAULT 0;
ALTER TABLE AttractionOpeningSchedule ADD COLUMN SCHEDULE_MESSAGE TEXT;

ALTER TABLE AttractionScheduleOverride ADD COLUMN OVERRIDE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE AttractionScheduleOverride ADD COLUMN OVERRIDE_END_DATE DATE;
ALTER TABLE AttractionScheduleOverride ADD COLUMN IS_CLOSED BOOL NOT NULL DEFAULT 1;
ALTER TABLE AttractionScheduleOverride ADD COLUMN OVERRIDE_MESSAGE TEXT;

ALTER TABLE ZoomobileRouteSchedule ADD COLUMN SCHEDULE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE ZoomobileRouteSchedule ADD COLUMN SCHEDULE_END_DATE DATE;
ALTER TABLE ZoomobileRouteSchedule ADD COLUMN ROUTE VARCHAR(16) NOT NULL DEFAULT 'summer';

ALTER TABLE ZoomobileStationStatus ADD COLUMN IS_CLOSED BOOL NOT NULL DEFAULT 0;
ALTER TABLE ZoomobileStationStatus ADD COLUMN CLOSED_MESSAGE TEXT;
ALTER TABLE ZoomobileStationStatus ADD COLUMN CLOSED_START DATE;
ALTER TABLE ZoomobileStationStatus ADD COLUMN CLOSED_END DATE;

ALTER TABLE GuardiansTalkSchedule ADD COLUMN SCHEDULE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE GuardiansTalkSchedule ADD COLUMN SCHEDULE_END_DATE DATE;
ALTER TABLE GuardiansTalkSchedule ADD COLUMN MONDAY_TIME VARCHAR(5);
ALTER TABLE GuardiansTalkSchedule ADD COLUMN TUESDAY_TIME VARCHAR(5);
ALTER TABLE GuardiansTalkSchedule ADD COLUMN WEDNESDAY_TIME VARCHAR(5);
ALTER TABLE GuardiansTalkSchedule ADD COLUMN THURSDAY_TIME VARCHAR(5);
ALTER TABLE GuardiansTalkSchedule ADD COLUMN FRIDAY_TIME VARCHAR(5);
ALTER TABLE GuardiansTalkSchedule ADD COLUMN SATURDAY_TIME VARCHAR(5);
ALTER TABLE GuardiansTalkSchedule ADD COLUMN SUNDAY_TIME VARCHAR(5);
ALTER TABLE GuardiansTalkSchedule ADD COLUMN SCHEDULE_MESSAGE TEXT;

ALTER TABLE GuardiansTalkCancellation ADD COLUMN CANCELLATION_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE GuardiansTalkCancellation ADD COLUMN TALK_TIME TEXT NOT NULL DEFAULT "";

ALTER TABLE WildEncounterSchedule ADD COLUMN SCHEDULE_START_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE WildEncounterSchedule ADD COLUMN SCHEDULE_END_DATE DATE;
ALTER TABLE WildEncounterSchedule ADD COLUMN MONDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE WildEncounterSchedule ADD COLUMN TUESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE WildEncounterSchedule ADD COLUMN WEDNESDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE WildEncounterSchedule ADD COLUMN THURSDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE WildEncounterSchedule ADD COLUMN FRIDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE WildEncounterSchedule ADD COLUMN SATURDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE WildEncounterSchedule ADD COLUMN SUNDAY BOOL NOT NULL DEFAULT 0;
ALTER TABLE WildEncounterSchedule ADD COLUMN ENCOUNTER_TIME TEXT NOT NULL DEFAULT "";
ALTER TABLE WildEncounterSchedule ADD COLUMN SCHEDULE_MESSAGE TEXT;

ALTER TABLE WildEncounterCancellation ADD COLUMN CANCELLATION_DATE DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE WildEncounterCancellation ADD COLUMN ENCOUNTER_TIME TEXT NOT NULL DEFAULT "";

ALTER TABLE DrinkingFountainStatus ADD COLUMN IS_CLOSED BOOL NOT NULL DEFAULT 0;
ALTER TABLE DrinkingFountainStatus ADD COLUMN START_DATE DATE;
ALTER TABLE DrinkingFountainStatus ADD COLUMN END_DATE DATE;
ALTER TABLE DrinkingFountainStatus ADD COLUMN CLOSED_MESSAGE TEXT;

ALTER TABLE ItineraryDate ADD COLUMN ARRIVAL_TIME TEXT;
ALTER TABLE ItineraryDate ADD COLUMN DEPARTURE_TIME TEXT;

ALTER TABLE ItineraryAnimal ADD COLUMN EXHIBIT VARCHAR(64) NOT NULL DEFAULT "";
ALTER TABLE ItineraryAnimal ADD COLUMN OLD_LIKELIHOOD INTEGER;
ALTER TABLE ItineraryAnimal ADD COLUMN NEW_LIKELIHOOD INTEGER;
ALTER TABLE ItineraryAnimal ADD COLUMN IS_ADDED BOOL NOT NULL DEFAULT 0;
ALTER TABLE ItineraryAnimal ADD COLUMN START_TIME TEXT;
ALTER TABLE ItineraryAnimal ADD COLUMN END_TIME TEXT;

ALTER TABLE ItineraryAttraction ADD COLUMN OLD_LIKELIHOOD INTEGER;
ALTER TABLE ItineraryAttraction ADD COLUMN NEW_LIKELIHOOD INTEGER;
ALTER TABLE ItineraryAttraction ADD COLUMN START_TIME TEXT;
ALTER TABLE ItineraryAttraction ADD COLUMN END_TIME TEXT;

ALTER TABLE ItineraryGuardiansTalk ADD COLUMN START_TIME TEXT;
ALTER TABLE ItineraryGuardiansTalk ADD COLUMN END_TIME TEXT;
ALTER TABLE ItineraryGuardiansTalk ADD COLUMN IS_DELETED BOOL NOT NULL DEFAULT 0;

ALTER TABLE ItineraryWildEncounter ADD COLUMN START_TIME TEXT;
ALTER TABLE ItineraryWildEncounter ADD COLUMN END_TIME TEXT;
ALTER TABLE ItineraryWildEncounter ADD COLUMN IS_DELETED BOOL NOT NULL DEFAULT 0;

ALTER TABLE ItineraryEvent ADD COLUMN START_TIME TEXT;
ALTER TABLE ItineraryEvent ADD COLUMN END_TIME TEXT;
