DROP TABLE IF EXISTS GuardiansTalkScheduleMigration;

CREATE TABLE GuardiansTalkScheduleMigration
(  TALK_NAME              VARCHAR(64) NOT NULL,
   LOCATION               VARCHAR(64) NOT NULL,
   SCHEDULE_START_DATE    DATE        NOT NULL,
   SCHEDULE_END_DATE      DATE,
   MONDAY_TIME            VARCHAR(5),
   TUESDAY_TIME           VARCHAR(5),
   WEDNESDAY_TIME         VARCHAR(5),
   THURSDAY_TIME          VARCHAR(5),
   FRIDAY_TIME            VARCHAR(5),
   SATURDAY_TIME          VARCHAR(5),
   SUNDAY_TIME            VARCHAR(5),
   SCHEDULE_MESSAGE       TEXT,
   PRIMARY KEY (TALK_NAME, LOCATION, SCHEDULE_START_DATE),
   FOREIGN KEY (TALK_NAME, LOCATION) REFERENCES MeetTheGuardiansTalk(NAME, LOCATION) );

INSERT OR IGNORE INTO GuardiansTalkScheduleMigration (
   TALK_NAME,
   LOCATION,
   SCHEDULE_START_DATE,
   SCHEDULE_END_DATE,
   MONDAY_TIME,
   TUESDAY_TIME,
   WEDNESDAY_TIME,
   THURSDAY_TIME,
   FRIDAY_TIME,
   SATURDAY_TIME,
   SUNDAY_TIME,
   SCHEDULE_MESSAGE
)
SELECT
   TALK_NAME,
   LOCATION,
   SCHEDULE_START_DATE,
   SCHEDULE_END_DATE,
   MONDAY_TIME,
   TUESDAY_TIME,
   WEDNESDAY_TIME,
   THURSDAY_TIME,
   FRIDAY_TIME,
   SATURDAY_TIME,
   SUNDAY_TIME,
   SCHEDULE_MESSAGE
FROM GuardiansTalkSchedule;

DROP TABLE GuardiansTalkSchedule;

ALTER TABLE GuardiansTalkScheduleMigration RENAME TO GuardiansTalkSchedule;
