DROP TABLE IF EXISTS GuardiansTalkScheduleMigration;

CREATE TABLE GuardiansTalkScheduleMigration
(  TALK_NAME              VARCHAR(64) NOT NULL,
   LOCATION               VARCHAR(64) NOT NULL,
   SCHEDULE_START_DATE    DATE        NOT NULL,
   SCHEDULE_END_DATE      DATE,
   MONDAY                 BOOL        NOT NULL DEFAULT 0,
   TUESDAY                BOOL        NOT NULL DEFAULT 0,
   WEDNESDAY              BOOL        NOT NULL DEFAULT 0,
   THURSDAY               BOOL        NOT NULL DEFAULT 0,
   FRIDAY                 BOOL        NOT NULL DEFAULT 0,
   SATURDAY               BOOL        NOT NULL DEFAULT 0,
   SUNDAY                 BOOL        NOT NULL DEFAULT 0,
   TALK_TIME              TEXT        NOT NULL,
   SCHEDULE_MESSAGE       TEXT,
   PRIMARY KEY (TALK_NAME, LOCATION, TALK_TIME, SCHEDULE_START_DATE),
   FOREIGN KEY (TALK_NAME, LOCATION) REFERENCES MeetTheGuardiansTalk(NAME, LOCATION) );

INSERT OR IGNORE INTO GuardiansTalkScheduleMigration (
   TALK_NAME,
   LOCATION,
   SCHEDULE_START_DATE,
   SCHEDULE_END_DATE,
   MONDAY,
   TUESDAY,
   WEDNESDAY,
   THURSDAY,
   FRIDAY,
   SATURDAY,
   SUNDAY,
   TALK_TIME,
   SCHEDULE_MESSAGE
)
SELECT
   TALK_NAME,
   LOCATION,
   SCHEDULE_START_DATE,
   MAX( SCHEDULE_END_DATE ),
   MAX( MONDAY ),
   MAX( TUESDAY ),
   MAX( WEDNESDAY ),
   MAX( THURSDAY ),
   MAX( FRIDAY ),
   MAX( SATURDAY ),
   MAX( SUNDAY ),
   TALK_TIME,
   MAX( SCHEDULE_MESSAGE )
FROM (
   SELECT
      TALK_NAME,
      LOCATION,
      SCHEDULE_START_DATE,
      SCHEDULE_END_DATE,
      1 AS MONDAY,
      0 AS TUESDAY,
      0 AS WEDNESDAY,
      0 AS THURSDAY,
      0 AS FRIDAY,
      0 AS SATURDAY,
      0 AS SUNDAY,
      MONDAY_TIME AS TALK_TIME,
      SCHEDULE_MESSAGE
   FROM GuardiansTalkSchedule
   WHERE MONDAY_TIME IS NOT NULL
      AND TRIM( MONDAY_TIME ) != ''

   UNION ALL

   SELECT
      TALK_NAME,
      LOCATION,
      SCHEDULE_START_DATE,
      SCHEDULE_END_DATE,
      0 AS MONDAY,
      1 AS TUESDAY,
      0 AS WEDNESDAY,
      0 AS THURSDAY,
      0 AS FRIDAY,
      0 AS SATURDAY,
      0 AS SUNDAY,
      TUESDAY_TIME AS TALK_TIME,
      SCHEDULE_MESSAGE
   FROM GuardiansTalkSchedule
   WHERE TUESDAY_TIME IS NOT NULL
      AND TRIM( TUESDAY_TIME ) != ''

   UNION ALL

   SELECT
      TALK_NAME,
      LOCATION,
      SCHEDULE_START_DATE,
      SCHEDULE_END_DATE,
      0 AS MONDAY,
      0 AS TUESDAY,
      1 AS WEDNESDAY,
      0 AS THURSDAY,
      0 AS FRIDAY,
      0 AS SATURDAY,
      0 AS SUNDAY,
      WEDNESDAY_TIME AS TALK_TIME,
      SCHEDULE_MESSAGE
   FROM GuardiansTalkSchedule
   WHERE WEDNESDAY_TIME IS NOT NULL
      AND TRIM( WEDNESDAY_TIME ) != ''

   UNION ALL

   SELECT
      TALK_NAME,
      LOCATION,
      SCHEDULE_START_DATE,
      SCHEDULE_END_DATE,
      0 AS MONDAY,
      0 AS TUESDAY,
      0 AS WEDNESDAY,
      1 AS THURSDAY,
      0 AS FRIDAY,
      0 AS SATURDAY,
      0 AS SUNDAY,
      THURSDAY_TIME AS TALK_TIME,
      SCHEDULE_MESSAGE
   FROM GuardiansTalkSchedule
   WHERE THURSDAY_TIME IS NOT NULL
      AND TRIM( THURSDAY_TIME ) != ''

   UNION ALL

   SELECT
      TALK_NAME,
      LOCATION,
      SCHEDULE_START_DATE,
      SCHEDULE_END_DATE,
      0 AS MONDAY,
      0 AS TUESDAY,
      0 AS WEDNESDAY,
      0 AS THURSDAY,
      1 AS FRIDAY,
      0 AS SATURDAY,
      0 AS SUNDAY,
      FRIDAY_TIME AS TALK_TIME,
      SCHEDULE_MESSAGE
   FROM GuardiansTalkSchedule
   WHERE FRIDAY_TIME IS NOT NULL
      AND TRIM( FRIDAY_TIME ) != ''

   UNION ALL

   SELECT
      TALK_NAME,
      LOCATION,
      SCHEDULE_START_DATE,
      SCHEDULE_END_DATE,
      0 AS MONDAY,
      0 AS TUESDAY,
      0 AS WEDNESDAY,
      0 AS THURSDAY,
      0 AS FRIDAY,
      1 AS SATURDAY,
      0 AS SUNDAY,
      SATURDAY_TIME AS TALK_TIME,
      SCHEDULE_MESSAGE
   FROM GuardiansTalkSchedule
   WHERE SATURDAY_TIME IS NOT NULL
      AND TRIM( SATURDAY_TIME ) != ''

   UNION ALL

   SELECT
      TALK_NAME,
      LOCATION,
      SCHEDULE_START_DATE,
      SCHEDULE_END_DATE,
      0 AS MONDAY,
      0 AS TUESDAY,
      0 AS WEDNESDAY,
      0 AS THURSDAY,
      0 AS FRIDAY,
      0 AS SATURDAY,
      1 AS SUNDAY,
      SUNDAY_TIME AS TALK_TIME,
      SCHEDULE_MESSAGE
   FROM GuardiansTalkSchedule
   WHERE SUNDAY_TIME IS NOT NULL
      AND TRIM( SUNDAY_TIME ) != ''
)
GROUP BY
   TALK_NAME,
   LOCATION,
   SCHEDULE_START_DATE,
   TALK_TIME;

DROP TABLE GuardiansTalkSchedule;

ALTER TABLE GuardiansTalkScheduleMigration RENAME TO GuardiansTalkSchedule;
