DROP TABLE IF EXISTS GuardiansTalkAnimalMigration;

CREATE TABLE GuardiansTalkAnimalMigration
(  TALK_NAME       VARCHAR(64) NOT NULL,
   LOCATION        VARCHAR(64) NOT NULL,
   SPECIES         VARCHAR(64) NOT NULL,
   EXHIBIT         VARCHAR(64) NOT NULL,
   ENCLOSURE_NAME  VARCHAR(64),
   PRIMARY KEY (TALK_NAME, LOCATION, SPECIES, EXHIBIT),
   FOREIGN KEY (TALK_NAME, LOCATION) REFERENCES MeetTheGuardiansTalk(NAME, LOCATION),
   FOREIGN KEY (SPECIES, EXHIBIT) REFERENCES Enclosure(SPECIES, EXHIBIT),
   FOREIGN KEY (SPECIES, EXHIBIT, ENCLOSURE_NAME)
      REFERENCES EnclosureViewing(SPECIES, EXHIBIT, NAME) );

INSERT OR IGNORE INTO GuardiansTalkAnimalMigration (
   TALK_NAME,
   LOCATION,
   SPECIES,
   EXHIBIT,
   ENCLOSURE_NAME
)
SELECT
   TALK_NAME,
   LOCATION,
   SPECIES,
   EXHIBIT,
   NULL
FROM GuardiansTalkAnimal;

DROP TABLE GuardiansTalkAnimal;

ALTER TABLE GuardiansTalkAnimalMigration RENAME TO GuardiansTalkAnimal;
