CREATE TABLE IF NOT EXISTS AnimalStatusEnclosureScoped
(  SPECIES              VARCHAR(64) NOT NULL,
   EXHIBIT              VARCHAR(64) NOT NULL,
   VIEWING_SCOPE        TEXT        NOT NULL,
   IS_OFF_DISPLAY       BOOL        NOT NULL DEFAULT 0,
   OFF_DISPLAY_MESSAGE  TEXT,
   OFF_DISPLAY_START    DATE,
   OFF_DISPLAY_END      DATE,
   PRIMARY KEY (SPECIES, EXHIBIT, VIEWING_SCOPE),
   FOREIGN KEY (SPECIES) REFERENCES Animal(SPECIES),
   FOREIGN KEY (EXHIBIT) REFERENCES Exhibit(NAME) );

INSERT OR IGNORE INTO AnimalStatusEnclosureScoped (
   SPECIES,
   EXHIBIT,
   VIEWING_SCOPE,
   IS_OFF_DISPLAY,
   OFF_DISPLAY_MESSAGE,
   OFF_DISPLAY_START,
   OFF_DISPLAY_END
)
SELECT
   s.SPECIES,
   s.EXHIBIT,
   COALESCE( v.NAME, '' ),
   s.IS_OFF_DISPLAY,
   s.OFF_DISPLAY_MESSAGE,
   s.OFF_DISPLAY_START,
   s.OFF_DISPLAY_END
FROM AnimalStatus s
JOIN EnclosureViewing v
   ON s.SPECIES = v.SPECIES
   AND s.EXHIBIT = v.EXHIBIT
WHERE LOWER( s.VIEWING_SCOPE ) = 'all'
   OR LOWER( s.VIEWING_SCOPE ) = LOWER( v.ENCLOSURE_TYPE )
   OR s.VIEWING_SCOPE = COALESCE( v.NAME, '' );

DROP TABLE AnimalStatus;

ALTER TABLE AnimalStatusEnclosureScoped
RENAME TO AnimalStatus;
