export class SuiteManifest {
   static SUITES = Object.freeze([
      { id: 'MAP-01', group: 'map', title: 'Baseline load and chrome', path: '/docs/manual-tests/map/MAP-01-baseline-load-and-chrome.json' },
      { id: 'MAP-02', group: 'map', title: 'Date presets', path: '/docs/manual-tests/map/MAP-02-date-presets.json' },
      { id: 'MAP-03', group: 'map', title: 'Type filters and search', path: '/docs/manual-tests/map/MAP-03-type-filters-and-search.json' },
      { id: 'MAP-04', group: 'map', title: 'Markers, likelihood, stacks', path: '/docs/manual-tests/map/MAP-04-markers-likelihood-stacks.json' },
      { id: 'MAP-05', group: 'map', title: 'Tooltips and species overlay', path: '/docs/manual-tests/map/MAP-05-tooltips-and-species-overlay.json' },
      { id: 'MAP-06', group: 'map', title: 'Off-display and closed toggles', path: '/docs/manual-tests/map/MAP-06-off-display-and-closed-toggles.json' },
      { id: 'MAP-07', group: 'map', title: 'Zoomobile routes', path: '/docs/manual-tests/map/MAP-07-zoomobile-routes.json' },
      { id: 'MAP-08', group: 'map', title: 'Closed exhibits and Updates/Events', path: '/docs/manual-tests/map/MAP-08-closed-exhibits-updates-events.json' },
      { id: 'MAP-09', group: 'map', title: 'Deep link focus', path: '/docs/manual-tests/map/MAP-09-deep-link-focus.json' },
      { id: 'MAP-10', group: 'map', title: 'Narrow layout smoke', path: '/docs/manual-tests/map/MAP-10-narrow-layout-smoke.json' },
      { id: 'ITIN-01', group: 'itinerary', title: 'Wizard happy path', path: '/docs/manual-tests/itinerary/ITIN-01-wizard-happy-path.json' },
      { id: 'ITIN-02', group: 'itinerary', title: 'Empty finish and clear', path: '/docs/manual-tests/itinerary/ITIN-02-empty-finish-and-clear.json' },
      { id: 'ITIN-03', group: 'itinerary', title: 'Arrival, departure, early admission', path: '/docs/manual-tests/itinerary/ITIN-03-arrival-departure-early-admission.json' },
      { id: 'ITIN-04', group: 'itinerary', title: 'Schedule module', path: '/docs/manual-tests/itinerary/ITIN-04-schedule-module.json' },
      { id: 'ITIN-05', group: 'itinerary', title: 'Rebuild and unschedule all', path: '/docs/manual-tests/itinerary/ITIN-05-rebuild-and-unschedule-all.json' },
      { id: 'ITIN-06', group: 'itinerary', title: 'Off-display / low-likelihood confirm', path: '/docs/manual-tests/itinerary/ITIN-06-off-display-low-likelihood-confirm.json' },
      { id: 'ITIN-07', group: 'itinerary', title: 'Talk and encounter scheduling', path: '/docs/manual-tests/itinerary/ITIN-07-talk-and-encounter-scheduling.json' },
      { id: 'ITIN-08', group: 'itinerary', title: 'Conflict and overlap flows', path: '/docs/manual-tests/itinerary/ITIN-08-conflict-and-overlap-flows.json' },
      { id: 'ITIN-09', group: 'itinerary', title: 'Attraction hours and transport prompts', path: '/docs/manual-tests/itinerary/ITIN-09-attraction-hours-and-transport-prompts.json' },
      { id: 'ITIN-10', group: 'itinerary', title: 'Bulk schedule pressure', path: '/docs/manual-tests/itinerary/ITIN-10-bulk-schedule-pressure.json' },
      { id: 'ITIN-11', group: 'itinerary', title: 'Draft and past-date recovery', path: '/docs/manual-tests/itinerary/ITIN-11-draft-and-past-date-recovery.json' },
      { id: 'ITIN-12', group: 'itinerary', title: 'Map path smoke', path: '/docs/manual-tests/itinerary/ITIN-12-map-path-smoke.json' },
      { id: 'CON-01', group: 'console', title: 'Animal off/on display', path: '/docs/manual-tests/console/CON-01-animal-off-on-display.json' },
      { id: 'CON-02', group: 'console', title: 'Visibility schedule', path: '/docs/manual-tests/console/CON-02-visibility-schedule.json' },
      { id: 'CON-03', group: 'console', title: 'Animal viewing alert', path: '/docs/manual-tests/console/CON-03-animal-viewing-alert.json' },
      { id: 'CON-04', group: 'console', title: 'Exhibit closed/open', path: '/docs/manual-tests/console/CON-04-exhibit-closed-open.json' },
      { id: 'CON-05', group: 'console', title: 'Restaurant closed / override / schedule', path: '/docs/manual-tests/console/CON-05-restaurant-closed-override-schedule.json' },
      { id: 'CON-06', group: 'console', title: 'Restroom closed/open + alert', path: '/docs/manual-tests/console/CON-06-restroom-closed-open-alert.json' },
      { id: 'CON-07', group: 'console', title: 'Gift shop closed / override / schedule', path: '/docs/manual-tests/console/CON-07-gift-shop-closed-override-schedule.json' },
      { id: 'CON-08', group: 'console', title: 'Attraction closed / override / schedule / hours', path: '/docs/manual-tests/console/CON-08-attraction-closed-override-schedule-hours.json' },
      { id: 'CON-09', group: 'console', title: 'Transportation station + route', path: '/docs/manual-tests/console/CON-09-transportation-station-and-route.json' },
      { id: 'CON-10', group: 'console', title: 'Guardians talks', path: '/docs/manual-tests/console/CON-10-guardians-talks.json' },
      { id: 'CON-11', group: 'console', title: 'Wild encounters', path: '/docs/manual-tests/console/CON-11-wild-encounters.json' },
      { id: 'CON-12', group: 'console', title: 'Drinking fountains', path: '/docs/manual-tests/console/CON-12-drinking-fountains.json' },
      { id: 'CON-13', group: 'console', title: 'Updates CRUD', path: '/docs/manual-tests/console/CON-13-updates-crud.json' },
      { id: 'CON-14', group: 'console', title: 'Create event', path: '/docs/manual-tests/console/CON-14-create-event.json' },
      { id: 'CON-15', group: 'console', title: 'Console validation matrix', path: '/docs/manual-tests/console/CON-15-console-validation-matrix.json' },
   ]);

   static GROUP_LABELS = Object.freeze({
      map: 'Map',
      itinerary: 'Itinerary',
      console: 'Console',
   });
}
