from __future__ import annotations

from .animal_day_seasonal_viewability_multiplier_seed_table import AnimalDaySeasonalViewabilityMultiplierSeedTable
from .animal_seed_table import AnimalSeedTable
from .animal_status_seed_table import AnimalStatusSeedTable
from .animal_viewing_alert_seed_table import AnimalViewingAlertSeedTable
from .animal_visibility_schedule_seed_table import AnimalVisibilityScheduleSeedTable
from .app_setting_seed_table import AppSettingSeedTable
from .attraction_animal_seed_table import AttractionAnimalSeedTable
from .attraction_day_seasonal_availability_multiplier_seed_table import AttractionDaySeasonalAvailabilityMultiplierSeedTable
from .attraction_hours_schedule_seed_table import AttractionHoursScheduleSeedTable
from .attraction_opening_schedule_seed_table import AttractionOpeningScheduleSeedTable
from .attraction_schedule_override_seed_table import AttractionScheduleOverrideSeedTable
from .attraction_seed_table import AttractionSeedTable
from .defibrillator_seed_table import DefibrillatorSeedTable
from .drinking_fountain_day_seasonal_availability_multiplier_seed_table import DrinkingFountainDaySeasonalAvailabilityMultiplierSeedTable
from .drinking_fountain_seed_table import DrinkingFountainSeedTable
from .drinking_fountain_status_seed_table import DrinkingFountainStatusSeedTable
from .emergency_intercom_seed_table import EmergencyIntercomSeedTable
from .enclosure_seed_table import EnclosureSeedTable
from .enclosure_viewing_seed_table import EnclosureViewingSeedTable
from .event_site_seed_table import EventSiteSeedTable
from .exhibit_day_seasonal_availability_multiplier_seed_table import ExhibitDaySeasonalAvailabilityMultiplierSeedTable
from .exhibit_seed_table import ExhibitSeedTable
from .exhibit_status_seed_table import ExhibitStatusSeedTable
from .gift_shop_day_seasonal_availability_multiplier_seed_table import GiftShopDaySeasonalAvailabilityMultiplierSeedTable
from .gift_shop_opening_schedule_seed_table import GiftShopOpeningScheduleSeedTable
from .gift_shop_schedule_override_seed_table import GiftShopScheduleOverrideSeedTable
from .gift_shop_seed_table import GiftShopSeedTable
from .guardians_talk_animal_seed_table import GuardiansTalkAnimalSeedTable
from .guardians_talk_cancellation_seed_table import GuardiansTalkCancellationSeedTable
from .guardians_talk_occurrence_seed_table import GuardiansTalkOccurrenceSeedTable
from .guardians_talk_schedule_seed_table import GuardiansTalkScheduleSeedTable
from .guest_service_seed_table import GuestServiceSeedTable
from .itinerary_animal_seed_table import ItineraryAnimalSeedTable
from .itinerary_attraction_seed_table import ItineraryAttractionSeedTable
from .itinerary_date_seed_table import ItineraryDateSeedTable
from .itinerary_event_default_seed_table import ItineraryEventDefaultSeedTable
from .itinerary_event_seed_table import ItineraryEventSeedTable
from .itinerary_exhibit_seed_table import ItineraryExhibitSeedTable
from .itinerary_guardians_talk_seed_table import ItineraryGuardiansTalkSeedTable
from .itinerary_status_seed_table import ItineraryStatusSeedTable
from .itinerary_status_suppression_seed_table import ItineraryStatusSuppressionSeedTable
from .itinerary_transportation_leg_seed_table import ItineraryTransportationLegSeedTable
from .itinerary_transportation_route_marker_seed_table import ItineraryTransportationRouteMarkerSeedTable
from .itinerary_transportation_seed_table import ItineraryTransportationSeedTable
from .itinerary_walk_route_leg_seed_table import ItineraryWalkRouteLegSeedTable
from .itinerary_walk_route_point_seed_table import ItineraryWalkRoutePointSeedTable
from .itinerary_walk_route_stop_seed_table import ItineraryWalkRouteStopSeedTable
from .itinerary_wild_encounter_seed_table import ItineraryWildEncounterSeedTable
from .legacy_table_drops_seed_table import LegacyTableDropsSeedTable
from .meet_the_guardians_talk_seed_table import MeetTheGuardiansTalkSeedTable
from .pavilion_seed_table import PavilionSeedTable
from .picnic_site_seed_table import PicnicSiteSeedTable
from .region_seed_table import RegionSeedTable
from .restaurant_day_seasonal_availability_multiplier_seed_table import RestaurantDaySeasonalAvailabilityMultiplierSeedTable
from .restaurant_opening_schedule_seed_table import RestaurantOpeningScheduleSeedTable
from .restaurant_schedule_override_seed_table import RestaurantScheduleOverrideSeedTable
from .restaurant_seed_table import RestaurantSeedTable
from .restroom_alert_seed_table import RestroomAlertSeedTable
from .restroom_seed_table import RestroomSeedTable
from .restroom_status_seed_table import RestroomStatusSeedTable
from .transportation_day_route_seed_table import TransportationDayRouteSeedTable
from .transportation_leg_seed_table import TransportationLegSeedTable
from .transportation_route_leg_marker_seed_table import TransportationRouteLegMarkerSeedTable
from .transportation_route_leg_seed_table import TransportationRouteLegSeedTable
from .transportation_route_schedule_seed_table import TransportationRouteScheduleSeedTable
from .transportation_route_seed_table import TransportationRouteSeedTable
from .transportation_route_station_seed_table import TransportationRouteStationSeedTable
from .transportation_seed_table import TransportationSeedTable
from .transportation_station_seed_table import TransportationStationSeedTable
from .transportation_station_status_seed_table import TransportationStationStatusSeedTable
from .wild_encounter_cancellation_seed_table import WildEncounterCancellationSeedTable
from .wild_encounter_meeting_spot_seed_table import WildEncounterMeetingSpotSeedTable
from .wild_encounter_schedule_seed_table import WildEncounterScheduleSeedTable
from .wild_encounter_seed_table import WildEncounterSeedTable
from .zoo_event_seed_table import ZooEventSeedTable
from .zoo_hours_seed_table import ZooHoursSeedTable
from .zoo_update_seed_table import ZooUpdateSeedTable

static_tables = [
   RegionSeedTable,
   ExhibitSeedTable,
   ExhibitDaySeasonalAvailabilityMultiplierSeedTable,
   AnimalSeedTable,
   EnclosureSeedTable,
   EnclosureViewingSeedTable,
   AnimalDaySeasonalViewabilityMultiplierSeedTable,
   PavilionSeedTable,
   RestaurantSeedTable,
   RestaurantDaySeasonalAvailabilityMultiplierSeedTable,
   RestroomSeedTable,
   GiftShopSeedTable,
   GiftShopDaySeasonalAvailabilityMultiplierSeedTable,
   ItineraryEventDefaultSeedTable,
   ItineraryStatusSeedTable,
   AttractionSeedTable,
   AttractionAnimalSeedTable,
   AttractionDaySeasonalAvailabilityMultiplierSeedTable,
   TransportationSeedTable,
   TransportationStationSeedTable,
   TransportationRouteSeedTable,
   TransportationRouteStationSeedTable,
   TransportationDayRouteSeedTable,
   TransportationLegSeedTable,
   TransportationRouteLegSeedTable,
   TransportationRouteLegMarkerSeedTable,
   MeetTheGuardiansTalkSeedTable,
   GuardiansTalkAnimalSeedTable,
   WildEncounterMeetingSpotSeedTable,
   WildEncounterSeedTable,
   DrinkingFountainDaySeasonalAvailabilityMultiplierSeedTable,
   DrinkingFountainSeedTable,
   DefibrillatorSeedTable,
   EmergencyIntercomSeedTable,
   GuestServiceSeedTable,
   PicnicSiteSeedTable,
   EventSiteSeedTable,
   ZooHoursSeedTable,
]

runtime_tables = [
   LegacyTableDropsSeedTable,
   AnimalStatusSeedTable,
   AnimalVisibilityScheduleSeedTable,
   AnimalViewingAlertSeedTable,
   ExhibitStatusSeedTable,
   RestroomStatusSeedTable,
   RestroomAlertSeedTable,
   ZooEventSeedTable,
   ZooUpdateSeedTable,
   RestaurantOpeningScheduleSeedTable,
   RestaurantScheduleOverrideSeedTable,
   GiftShopOpeningScheduleSeedTable,
   GiftShopScheduleOverrideSeedTable,
   AppSettingSeedTable,
   AttractionOpeningScheduleSeedTable,
   AttractionHoursScheduleSeedTable,
   AttractionScheduleOverrideSeedTable,
   TransportationRouteScheduleSeedTable,
   TransportationStationStatusSeedTable,
   GuardiansTalkScheduleSeedTable,
   GuardiansTalkCancellationSeedTable,
   GuardiansTalkOccurrenceSeedTable,
   WildEncounterScheduleSeedTable,
   WildEncounterCancellationSeedTable,
   DrinkingFountainStatusSeedTable,
   ItineraryStatusSuppressionSeedTable,
   ItineraryDateSeedTable,
   ItineraryExhibitSeedTable,
   ItineraryAnimalSeedTable,
   ItineraryAttractionSeedTable,
   ItineraryTransportationSeedTable,
   ItineraryTransportationLegSeedTable,
   ItineraryTransportationRouteMarkerSeedTable,
   ItineraryGuardiansTalkSeedTable,
   ItineraryWildEncounterSeedTable,
   ItineraryEventSeedTable,
   ItineraryWalkRouteStopSeedTable,
   ItineraryWalkRoutePointSeedTable,
   ItineraryWalkRouteLegSeedTable,
]
