from __future__ import annotations

from ..data_access.gift_shop_schedule import delete_gift_shop_opening_schedule
from ..data_access.gift_shop_schedule import fetch_gift_shop_opening_schedule_conflicts
from ..data_access.gift_shop_schedule import insert_copied_gift_shop_opening_schedule
from ..data_access.gift_shop_schedule import insert_or_update_gift_shop_opening_schedule
from ..data_access.gift_shop_schedule import update_gift_shop_opening_schedule_dates
from ...shared.build_opening_schedule_conflict_resolution import OpeningScheduleConflictResolution


_resolution = OpeningScheduleConflictResolution(
   fetch_conflicts=fetch_gift_shop_opening_schedule_conflicts,
   delete_conflict=delete_gift_shop_opening_schedule,
   insert_or_update=insert_or_update_gift_shop_opening_schedule,
   update_dates=update_gift_shop_opening_schedule_dates,
   insert_copy=insert_copied_gift_shop_opening_schedule,
)

save_gift_shop_opening_schedule_replacing_overlaps = _resolution.save_replacing_overlaps
save_gift_shop_opening_schedule_trimming_overlaps = _resolution.save_trimming_overlaps
trim_gift_shop_opening_schedule_conflict = _resolution.trim_conflict


__all__ = [
   'save_gift_shop_opening_schedule_replacing_overlaps',
   'save_gift_shop_opening_schedule_trimming_overlaps',
   'trim_gift_shop_opening_schedule_conflict',
]
